services:
  jenkins-master:
    image: jenkins/jenkins:lts
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"  # Keep if you might add agents later
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./conf/plugins.txt:/usr/share/jenkins/ref/plugins.txt
      - ./conf/jcasc.yaml:/var/jenkins_home/jcasc.yaml
      #  ./conf:/usr/share/jenkins/ref/init.groovy.d
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
      JENKINS_ADMIN_ID: "admin"
      JENKINS_ADMIN_PASSWORD: "admin"
    networks:
      - jenkins-net

volumes:
  jenkins_home:

networks:
  jenkins-net:
    driver: bridge